[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit PN532
  miguelbalboa/MFRC522
  chris--a/Keypad
  marcoschwartz/LiquidCrystal_I2C
